version: '3.7'

services:

  drupal:
    image: rnsrk/drupal-wisski
    build: 
      context: .
      dockerfile: Drupal-Dockerfile
    volumes: 
      - ./drupal-website:/var/www/html

    environment:
      VIRTUAL_HOST: ''
      LETSENCRYPT_HOST: ''
      LETSENCRYPT_EMAIL: ''
    networks:
      - default
      - proxy-network
  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=TestingWissKI   
    volumes:
      - ./drupal-data:/var/lib/mysql

  graphdb:
    image: dhlabbasel/graphdb-free
    volumes: 
      - ./graphdb-data:/graphdb/data/repositories
networks:
  proxy-network:
    name: global-proxy-network
    external: true
